// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyApp.proto

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 enroll_number = 2;</code>
   */
  int getEnrollNumber();

  /**
   * <code>float height = 3;</code>
   */
  float getHeight();

  /**
   * <code>repeated int32 luck_numbers = 4;</code>
   */
  java.util.List<java.lang.Integer> getLuckNumbersList();
  /**
   * <code>repeated int32 luck_numbers = 4;</code>
   */
  int getLuckNumbersCount();
  /**
   * <code>repeated int32 luck_numbers = 4;</code>
   */
  int getLuckNumbers(int index);
}
